name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main  # Gatilho para rodar o pipeline quando houver commits na branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c칩digo-fonte
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar o projeto com Maven
        run: |
          cd BlogPeriferico.BackEnd/blogPeriferia  # Ajustando o caminho para onde o pom.xml est치
          ls  # Lista arquivos para verificar se o pom.xml est치 correto
          mvn clean package -DskipTests  # Compila o projeto, ignorando testes

      - name: Upload do artefato para o job de deployment
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: BlogPeriferico.BackEnd/blogPeriferia/target/*.jar  # Ajustando caminho do JAR gerado

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: .  # Baixa para o diret칩rio raiz

      - name: Deploy na Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BlogPeriferico'  # Nome do App no Azure
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '*.jar'  # Deploy do arquivo gerado
