name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TCC-BACK-main

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Listar diretórios para depuração
        run: ls -R

      - name: Configurar cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('TCC-BACK-main/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Executar testes com Maven
        run: mvn test

      - name: Compilar o projeto com Maven
        run: mvn clean package

      - name: Copiar JAR para pasta de backup
        if: success()
        run: |
          mkdir -p ../backup
          cp target/*.jar ../backup/

      - name: Upload do artefato principal
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: TCC-BACK-main/target/*.jar

      - name: Upload do backup
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app-backup
          path: backup/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar artefato principal
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: .

      - name: Deploy na Azure App Service
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BlogPerigericoBackEnd'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '*.jar'

      - name: Criar issue no GitHub se falhar
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/deploy_fail.md

      - name: Baixar backup para rollback
        if: failure()
        uses: actions/download-artifact@v4
        with:
          name: springboot-app-backup
          path: rollback/

      - name: Rollback para versão anterior
        if: failure()
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BlogPerigericoBackEnd'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: 'rollback/*.jar'
