name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar o projeto com Maven
        run: |
          cd BlogPeriferico.BackEnd/blogPeriferia  
          
          mvn clean package -DskipTests  

      - name: Upload do artefato para o job de deployment
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: BlogPeriferico.BackEnd/blogPeriferia/target/*.jar 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: .  

      - name: Deploy na Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BlogPeriferico'  
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '*.jar' 
