name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # O fluxo de trabalho será disparado quando houver um commit na branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Usar a última versão do Ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Fazer checkout do repositório

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Configura o JDK 21 para o projeto

      - name: Navegar para o diretório correto e compilar o projeto com Maven
        run: |
          cd BlogPeriferico.BackEnd  # Navega para o diretório correto (ajuste conforme necessário)
          mvn clean package -DskipTests  # Executa o Maven para compilar o projeto

      - name: Fazer upload do arquivo JAR
        uses: actions/upload-artifact@v4  # Faz upload do arquivo JAR para ser usado na etapa de deploy
        with:
          name: app-artifact  # Nome do artefato
          path: target/*.jar  # Caminho do arquivo JAR gerado após o build

  deploy:
    runs-on: ubuntu-latest  # Usar a última versão do Ubuntu
    needs: build  # A etapa de deploy depende da etapa de build

    steps:
      - name: Baixar artefato da etapa de build
        uses: actions/download-artifact@v4  # Baixa o artefato gerado pelo build
        with:
          name: app-artifact  # Nome do artefato a ser baixado

      - name: Deploy para Azure App Service
        uses: azure/webapps-deploy@v2  # Ação para deploy no Azure Web App
        with:
          app-name: 'BlogPeriferico'  # Nome do seu aplicativo no Azure
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Perfil de publicação do Azure armazenado em Secrets
          package: '*.jar'  # Pacote a ser enviado para o Azure (o arquivo JAR)

