name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Configurar cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('TCC-BACK-main/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn -f TCC-BACK-main/pom.xml clean package -DskipTests

      - name: Upload do artefato para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: TCC-BACK-main/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: .

      - name: Deploy na Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BlogPerigericoBackEnd'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '*.jar'
