name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Exibir a estrutura de diretórios
        run: |
          echo "Estrutura de diretórios:"
          ls -R

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Navegar até o diretório correto onde o pom.xml está localizado
      - name: Navegar até o diretório correto
        run: cd BlogPeriferico.BackEnd

      - name: Compilar aplicação com Maven
        run: mvn clean package -DskipTests

      - name: Publicar no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "BlogPeriferia"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: target/*.jar
